#!/usr/bin/env python3
"""Parche de strings UI retail → marketplace OficiosHub (seguridad / mediación)."""

UI_PATCH: dict[str, object] = {
    "searchPlaceholder": "Buscar persona u oficio...",
    "noProductsTitle": "No encontramos a nadie con ese oficio",
    "noProductsMessage": "Probá Hogar, Electricidad, Pintura o Exterior",
    "homeCategoriesTitle": "Oficios",
    "homeCategoriesSubtitle": "Solo cuatro: elegí y mirá quién ofrece",
    "homeFeaturedTitle": "Personas destacadas",
    "homeFeaturedSubtitle": "Vecinos con oficio que más se contratan",
    "homeNewTitle": "Recién sumados",
    "homeNewSubtitle": "Personas que acaban de publicar su oficio",
    "homeSaleTitle": "Más contratados",
    "homeSaleSubtitle": "Personas con alta demanda en la plataforma",
    "homeViewAllLabel": "Ver todos",
    "headerAllProductsLabel": "Todos los oficios",
    "headerMyOrdersLabel": "Mis reservas",
    "footerWhatsappBody": "Ingresá tu número y recibí novedades de tus reservas (solo canal oficial)",
    "cartTitle": "Mi pedido",
    "cartEmptyTitle": "Todavía no elegiste a nadie",
    "cartEmptyBody": "Elegí una persona con oficio para armar tu pedido de servicio.",
    "cartEmptyExploreLabel": "Explorar oficios",
    "cartProceedAuthLabel": "Continuar con la reserva",
    "cartProceedGuestLabel": "Iniciar sesión para reservar",
    "cartClearLabel": "Vaciar pedido",
    "loginSubtitle": "Accedé para contratar con mediación de OficiosHub y seguir tus reservas",
    "productNotFoundTitle": "Servicio no encontrado",
    "productNotFoundBody": "Esa persona u oficio no existe o ya no está disponible",
    "productViewAllLabel": "Ver todos los oficios",
    "productBreadcrumbProducts": "Oficios",
    "productOutOfStockLabel": "No disponible",
    "productAddToCartLabel": "Pedir servicio",
    "productBuySecureTitle": "Contratación segura",
    "productBuySecureDesc": "OficiosHub intermedia: sin contacto directo y cobro tras tu OK de calidad",
    "productMultiplePaymentsTitle": "Pago con respaldo",
    "productMultiplePaymentsDesc": "El cobro se libera recién cuando das el OK de calidad",
    "cartPageTitle": "Tu pedido",
    "cartPageContinueShopping": "Seguir explorando",
    "cartPageItemsLabel": "Personas en tu pedido",
    "cartPageClearCartLabel": "Vaciar pedido",
    "cartPageProductSingular": "persona",
    "cartPageProductPlural": "personas",
    "cartPageShippingLabel": "Coordinación",
    "cartPageCheckoutLabel": "Continuar con la reserva",
    "cartPageSSLBadge": "Contratación intermediada",
    "cartPageSSLDesc": "La plataforma intermedia pedido, coordinación y cobro",
    "cartPageShippingBadge": "Visita coordinada",
    "cartPageShippingDesc": "Fecha, zona y detalle; el proveedor acepta por OficiosHub",
    "checkoutTitle": "Confirmar reserva",
    "checkoutBackLabel": "Volver al pedido",
    "checkoutStepShipping": "Visita",
    "checkoutShippingTitle": "Datos de la visita",
    "checkoutReviewTitle": "Revisá tu reserva",
    "checkoutAddressTitle": "Domicilio del servicio",
    "checkoutFieldAddress": "Dirección del servicio",
    "checkoutEfectivoDesc": "Pago habilitado en plataforma; se libera tras tu OK de calidad",
    "checkoutEfectivoNote": (
        "Recibirás confirmación por email. No hay contacto directo con la persona: "
        "todo se coordina por OficiosHub. El cobro se libera con tu OK de calidad."
    ),
    "checkoutTransferImportantNote": (
        "Si corresponde comprobante, envialo al WhatsApp oficial de OficiosHub con tu número de orden. "
        "No contactes a la persona por fuera de la plataforma."
    ),
    "checkoutCartEmptyMsg": "No tenés servicios en tu pedido para procesar",
    "checkoutViewProductsLabel": "Ver oficios",
    "checkoutShippingLabel": "Coordinación",
    "checkoutOrderTitle": "Resumen de la reserva",
    "checkoutFinalizeLabel": "Confirmar contratación",
    "footerCustomerTrackingLabel": "Seguimiento de reserva",
    "footerCustomerReturnsLabel": "Cambios / cancelaciones",
    "footerCustomerWarrantyLabel": "Calidad y reseñas",
    "footerCompanyAboutLabel": "Sobre OficiosHub",
    "registrationSuccessTitle": "¡Bienvenido a OficiosHub!",
    "registrationSuccessSubtitle": "Tu cuenta está lista para contratar con mediación",
    "registrationSuccessReadyTitle": "¡Todo listo!",
    "registrationSuccessBullet1": "Tu cuenta de cliente está activa",
    "registrationSuccessBullet2": "Podés pedir servicios con fecha, zona y detalle",
    "registrationSuccessBullet3": "Sin contacto directo: OficiosHub intermedia",
    "registrationSuccessBullet4": "El cobro se libera recién con tu OK de calidad",
    "registrationSuccessViewProductsLabel": "Ver personas y oficios",
    "registrationSuccessHomeLabel": "Ir al inicio",
    "orderSuccessTitle": "Reserva recibida",
    "orderSuccessSubtitle": (
        "Gracias. El proveedor debe aceptar la reserva. "
        "OficiosHub intermedia la coordinación y el cobro tras tu OK de calidad."
    ),
    "orderSuccessNextBullet1": "Recibirás un email con el número de orden",
    "orderSuccessNextBullet2": "El proveedor acepta o rechaza en su panel",
    "orderSuccessNextBullet3": "Cuando el trabajo esté hecho, das el OK de calidad en Mis reservas",
    "orderSuccessViewOrdersLabel": "Ver mis reservas",
    "orderSuccessContinueLabel": "Seguir explorando",
    "orderStatusPreparing": "En curso",
    "orderStatusReadyToShip": "Lista para visita",
    "orderStatusShipped": "En camino a la visita",
    "orderStatusInTransit": "En coordinación",
    "orderStatusOutForDelivery": "Visita en curso",
    "orderStatusDelivered": "Servicio realizado",
    "orderStatusCompleted": "Completada",
    "orderStatusReturnRequested": "Cancelación solicitada",
    "orderStatusReturnInTransit": "Cancelación en gestión",
    "orderStatusReturned": "Cancelada / reprogramada",
    "ordersPageTitle": "Mis reservas",
    "ordersAuthMessage": "Necesitás iniciar sesión para ver tus reservas",
    "ordersSearchPlaceholder": "Buscar por número de orden u oficio...",
    "ordersFilterShippedLabel": "En visita",
    "ordersFilterDeliveredLabel": "Realizado",
    "ordersEmptyTitle": "No tenés reservas aún",
    "ordersEmptyBody": "Cuando contrates a una persona, la reserva aparecerá aquí.",
    "ordersEmptyExploreLabel": "Explorar oficios",
    "ordersItemsCountLabel": "servicio(s)",
    "ordersDetailTitle": "Detalle de la reserva",
    "ordersDetailNotesLabel": "Notas / visita",
    "ordersDetailProductsLabel": "Servicios",
    "ordersDetailStorefrontNote": (
        "OficiosHub intermedia la reserva. El cobro se libera con tu OK de calidad. "
        "No compartimos contacto directo."
    ),
    "profileViewOrdersLabel": "Ver mis reservas",
    "favoritesEmptyBody": "Guardá personas u oficios para encontrarlos después.",
    "favoritesEmptyExploreLabel": "Explorar oficios",
    "favoritesCountSingular": "persona guardada",
    "favoritesCountPlural": "personas guardadas",
    "favoritesAddAllLabel": "Agregar todo al pedido",
    "trackingPageTitle": "Seguimiento de reserva",
    "trackingSubtitle": "Consultá el estado de tu contratación intermediada",
    "trackingWhatsappTitle": "Consultá por el canal oficial",
    "trackingWhatsappBody": (
        "Escribinos al WhatsApp oficial de OficiosHub con tu número de orden. "
        "No contactes a la persona por fuera de la plataforma."
    ),
    "trackingHowTitle": "¿Cómo funciona el seguimiento?",
    "trackingStep1Title": "Número de orden",
    "trackingStep1Body": "Al confirmar la reserva recibís un número de orden por email.",
    "trackingStep2Title": "Aceptación del proveedor",
    "trackingStep2Body": "La persona acepta o rechaza en su panel. Vos seguís el estado en Mis reservas.",
    "trackingStep3Title": "OK de calidad",
    "trackingStep3Body": "Cuando el trabajo esté hecho, das el OK de calidad y se libera el cobro.",
    "trackingStatusSectionTitle": "Estados de la reserva",
    "trackingStatus1Label": "Recibida",
    "trackingStatus1Desc": "Tu reserva fue registrada en OficiosHub",
    "trackingStatus2Label": "Aceptada / en curso",
    "trackingStatus2Desc": "El proveedor aceptó y se coordina la visita por la plataforma",
    "trackingStatus3Label": "Servicio realizado",
    "trackingStatus3Desc": "El trabajo se marcó como hecho; falta tu OK de calidad",
    "trackingStatus4Label": "Completada",
    "trackingStatus4Desc": "Diste OK de calidad y el cobro puede liberarse",
    "trackingFaq1Question": "¿Cuándo se coordina la visita?",
    "trackingFaq1Answer": (
        "Indicás fecha, hora y zona al pedir. El proveedor acepta por OficiosHub. "
        "No hay contacto directo entre las partes."
    ),
    "trackingFaq2Question": "¿Puedo modificar o cancelar?",
    "trackingFaq2Answer": (
        "Sí, escribinos por el canal oficial con tu número de orden. "
        "La viabilidad depende del estado (si aún no se realizó el trabajo suele ser más simple)."
    ),
    "trackingFaq3Question": "No recibí el número de orden",
    "trackingFaq3Answer": "Revisá spam. Si no está, contactá al WhatsApp oficial de OficiosHub.",
    "trackingFaq4Question": "¿Puedo pagar o hablar afuera de la plataforma?",
    "trackingFaq4Answer": (
        "No. OficiosHub intermedia para tu seguridad: coordinación y cobro pasan por la plataforma "
        "y el cobro se libera con tu OK de calidad."
    ),
    "contactPageTitle": "Centro de ayuda",
    "contactSubtitle": "Canal oficial de OficiosHub. No pedimos que contactes a la persona por fuera.",
    "contactOfficialChannelBody": "Medio oficial: WhatsApp de la plataforma. Respuesta del equipo OficiosHub.",
    "contactProductsTitle": "Consultas de oficios",
    "contactProductsBody": "¿Dudas sobre un servicio, zona o cómo pedir una reserva?",
    "contactTrackingTitle": "Seguimiento de reserva",
    "contactTrackingBody": "Consultá el estado de tu orden y el OK de calidad.",
    "contactB2bTitle": "Quiero ofrecer mi oficio",
    "contactB2bBody": "Registrate como persona particular; validamos idoneidad antes de publicar.",
    "contactB2bLabel": "Ofrecer mi oficio →",
    "contactReturnsTitle": "Cambios / cancelaciones",
    "contactReturnsBody": "Pedí cambios o cancelaciones de una reserva con tu número de orden.",
    "contactReturnsLabel": "Gestionar cambio →",
    "cartDrawerEmptyDescription": "Tu pedido está vacío",
    "cartDrawerCountSuffix": "en tu pedido",
    "cartItemRemovedTitle": "Quitado del pedido",
    "cartItemRemovedMessage": "La persona fue eliminada del pedido",
    "cartClearedTitle": "Pedido vaciado",
    "cartClearedMessage": "Se vació tu pedido",
    "productOutOfStockNotifTitle": "No disponible",
    "productOutOfStockNotifMessage": "Este servicio no está disponible ahora",
    "productLoginForFavoritesMessage": "Necesitás iniciar sesión para guardar personas en favoritos",
    "productVariantRequiredMessage": "Seleccioná las opciones necesarias antes de pedir el servicio.",
    "productVariantOutOfStockMessage": "Esa opción no está disponible.",
    "productWithVariantsLabel": "Servicio con opciones",
    "productAvailableUnitsLabel": "disponibles",
}
